# This is a basic workflow that is manually triggered

name: nudge-service

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master # Triggers deployment on push to the master branch
  pull_request:
    branches:
      - master # Optional: Triggers deployment on PR merge to master

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Deploy nudge-service"
        # Default value if no value is explicitly provided
        default: "nudge"
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{secrets.RENDER_API_KEY}}
        run: |
          curl -X POST \
          -H 'Accept: application/json' \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          https://api.render.com/v1/services/cr9rbrd6l47c73crs4q0/deploys
